import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SearchInput from '@/app/Components/SearchInput'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-zinc-200">
        <div className='flex flex-col items-center gap-10 p-6'>
          <SearchInput />
          <div className='flex flex-col items-center w-full'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
